server:
  port: 9092

spring:
  mvc.path match:
    matching-strategy: ant-path-matcher
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.200:3306/produto?createDatabaseIfNotExist=True
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  flyway:
    enable: false
    clean-disabled: true


